In [1]:
import json

In [5]:
def start_requests():
    print("Start Trip Advisor spider...")
    with open("data/cmu/offering.txt", 'r') as f:
        for hotel_data in f:
            hotel_data = json.loads(hotel_data.strip())
            url = hotel_data["url"]
            yield url
#         url = next(self.urls)
#         logger.info(f"Crawling {url}")
#         yield scrapy.Request(url=url, callback=self.parse)

gen = start_requests()
gen

In [6]:
next(gen)

Start Trip Advisor spider...

'http://www.tripadvisor.com/Hotel_Review-g60763-d113317-Reviews-Casablanca_Hotel_Times_Square-New_York_City_New_York.html'

In [7]:
next(gen)

'http://www.tripadvisor.com/Hotel_Review-g32655-d76049-Reviews-Four_Seasons_Hotel_Los_Angeles_at_Beverly_Hills-Los_Angeles_California.html'

In [8]:
next(gen)

'http://www.tripadvisor.com/Hotel_Review-g60763-d99352-Reviews-Hilton_Garden_Inn_Times_Square-New_York_City_New_York.html'

In [2]:
with open("data/cmu/offering.txt") as f:
    offering = [json.loads(jline) for jline in f.read().splitlines()]

In [3]:
len(offering)

4333

In [4]:
for entry in offering[:50]:
    print(entry["url"])

http://www.tripadvisor.com/Hotel_Review-g60763-d113317-Reviews-Casablanca_Hotel_Times_Square-New_York_City_New_York.html
http://www.tripadvisor.com/Hotel_Review-g32655-d76049-Reviews-Four_Seasons_Hotel_Los_Angeles_at_Beverly_Hills-Los_Angeles_California.html
http://www.tripadvisor.com/Hotel_Review-g60763-d99352-Reviews-Hilton_Garden_Inn_Times_Square-New_York_City_New_York.html
http://www.tripadvisor.com/Hotel_Review-g60763-d93589-Reviews-The_Michelangelo_Hotel-New_York_City_New_York.html
http://www.tripadvisor.com/Hotel_Review-g60763-d217616-Reviews-The_Muse_Hotel_New_York-New_York_City_New_York.html
http://www.tripadvisor.com/Hotel_Review-g60763-d208454-Reviews-Sofitel_New_York-New_York_City_New_York.html
http://www.tripadvisor.com/Hotel_Review-g60763-d2643161-Reviews-The_NoMad_Hotel-New_York_City_New_York.html
http://www.tripadvisor.com/Hotel_Review-g60763-d1465162-Reviews-Staybridge_Suites_Times_Square_New_York_City-New_York_City_New_York.html
http://www.tripadvisor.com/Hotel_Review-g60763-d93559-Reviews-The_Sherry_Netherland_Hotel-New_York_City_New_York.html
http://www.tripadvisor.com/Hotel_Review-g60763-d80112-Reviews-San_Carlos_Hotel-New_York_City_New_York.html
http://www.tripadvisor.com/Hotel_Review-g60763-d93396-Reviews-The_Iroquois-New_York_City_New_York.html
http://www.tripadvisor.com/Hotel_Review-g60763-d1456560-Reviews-Eventi_a_Kimpton_Hotel-New_York_City_New_York.html
http://www.tripadvisor.com/Hotel_Review-g60763-d1641016-Reviews-The_Chatwal-New_York_City_New_York.html
http://www.tripadvisor.com/Hotel_Review-g60763-d1776857-Reviews-The_Setai_Fifth_Avenue_a_Capella_managed_Hotel-New_York_City_New_York.html
http://www.tripadvisor.com/Hotel_Review-g60763-d1762573-Reviews-Andaz_5th_Avenue-New_York_City_New_York.html
http://www.tripadvisor.com/Hotel_Review-g60763-d93338-Reviews-Hotel_Beacon-New_York_City_New_York.html
http://www.tripadvisor.com/Hotel_Review-g60763-d224224-Reviews-The_Ritz_Carlton_New_York_Central_Park-New_York_City_New_York.html
http://www.tripadvisor.com/Hotel_Review-g56003-d1866401-Reviews-Holiday_Inn_Hotel_Houston_Westchase-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d99060-Reviews-Omni_Houston_Hotel-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d1218737-Reviews-La_Quinta_Inn_Suites_Houston_Normandy-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d99081-Reviews-Crowne_Plaza_Houston_Brookhollow-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d107915-Reviews-Drury_Inn_Suites_Houston_Near_The_Galleria-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d1966350-Reviews-The_Westin_Houston_Memorial_City-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d108038-Reviews-Hilton_University_of_Houston-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d1200103-Reviews-Hotel_Sorella_CITYCENTRE-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d283873-Reviews-Hotel_Icon_Autograph_Collection-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d98952-Reviews-Four_Seasons_Hotel_Houston-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d107956-Reviews-Extended_Stay_America_Houston_Northwest-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d1158926-Reviews-Hilton_Garden_Inn_Houston_Energy_Corridor-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d282699-Reviews-Hilton_Americas_Houston-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d239853-Reviews-BEST_WESTERN_PLUS_Downtown_Inn_Suites_Houston-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d665163-Reviews-Courtyard_by_Marriott_Houston_by_the_Galleria-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d111618-Reviews-Renaissance_Houston_Hotel_Greenway_Plaza-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d99114-Reviews-Westin_Galleria_Houston_Hotel-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d107924-Reviews-Courtyard_by_Marriott_Houston_Westchase-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d223151-Reviews-Hampton_Inn_and_Suites_Houston_Medical_Center_Reliant_Park-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d223137-Reviews-La_Quinta_Inn_Houston_Northwest-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d258636-Reviews-Alden_Houston-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d98920-Reviews-Houston_Marriott_Westchase-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d1236706-Reviews-Super_8_Houston_Hobby_Airport_South-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d108057-Reviews-Residence_Inn_Houston_Clear_Lake-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d240436-Reviews-Carefree_Inn_Medical_Center-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d266158-Reviews-Super_8_Houston_Hobby_Airport_I_45-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d559491-Reviews-Holiday_Inn_Express_Houston_East-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d1630591-Reviews-Crowne_Plaza-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d99106-Reviews-La_Quinta_Inn_Houston_Medical_Reliant_Center-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d242394-Reviews-Royal_Sonesta_Hotel_Houston-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d108148-Reviews-Holiday_Inn_Houston_Intercontinental_Airport-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d99067-Reviews-Four_Points_by_Sheraton_Houston_Memorial_City-Houston_Texas.html
http://www.tripadvisor.com/Hotel_Review-g56003-d585164-Reviews-Residence_Inn_Houston_West_Energy_Corridor-Houston_Texas.html

In [17]:
offering[1]

{'hotel_class': 5.0,
 'region_id': 32655,
 'url': 'http://www.tripadvisor.com/Hotel_Review-g32655-d76049-Reviews-Four_Seasons_Hotel_Los_Angeles_at_Beverly_Hills-Los_Angeles_California.html',
 'phone': '',
 'details': None,
 'address': {'region': 'CA',
  'street-address': '300 S Doheny Dr',
  'postal-code': '90048',
  'locality': 'Los Angeles'},
 'type': 'hotel',
 'id': 76049,
 'name': 'Four Seasons Hotel Los Angeles at Beverly Hills'}

In [18]:
with open("data/cmu/review.txt") as f:
    review = [json.loads(jline) for jline in f.read().splitlines()]

In [19]:
len(review)

878561

In [20]:
review[0]

{'ratings': {'service': 5.0,
  'cleanliness': 5.0,
  'overall': 5.0,
  'value': 5.0,
  'location': 5.0,
  'sleep_quality': 5.0,
  'rooms': 5.0},
 'title': '“Truly is "Jewel of the Upper Wets Side"”',
 'text': 'Stayed in a king suite for 11 nights and yes it cots us a bit but we were happy with the standard of room, the location and the friendliness of the staff. Our room was on the 20th floor overlooking Broadway and the madhouse of the Fairway Market. Room was quite with no noise evident from the hallway or adjoining rooms. It was great to be able to open windows when we craved fresh rather than heated air. The beds, including the fold out sofa bed, were comfortable and the rooms were cleaned well. Wi-fi access worked like a dream with only one connectivity issue on our first night and this was promptly responded to with a call from the service provider to ensure that all was well. The location close to the 72nd Street subway station is great and the complimentary umbrellas on the drizzly days were greatly appreciated. It is fabulous to have the kitchen with cooking facilities and the access to a whole range of fresh foods directly across the road at Fairway.\nThis is the second time that members of the party have stayed at the Beacon and it will certainly be our hotel of choice for future visits.',
 'author': {'username': 'Papa_Panda',
  'num_cities': 22,
  'num_helpful_votes': 12,
  'num_reviews': 29,
  'num_type_reviews': 24,
  'id': '8C0B42FF3C0FA366A21CFD785302A032',
  'location': 'Gold Coast'},
 'date_stayed': 'December 2012',
 'offering_id': 93338,
 'num_helpful_votes': 0,
 'date': 'December 17, 2012',
 'id': 147643103,
 'via_mobile': False}

# bah

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data/inside/listings.csv")
df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,761411,https://www.airbnb.com/rooms/761411,20230903194145,2023-09-03,city scrape,Condo in Amsterdam · ★4.74 · 1 bedroom · 1 bed...,"Really quiet, spacious and safe, a nice place ...","The neighborhood is very green, quiet, safe an...",https://a0.muscache.com/pictures/10591508/bf30...,4013546,...,4.92,4.42,4.65,0363 D4AD DCF3 E72A 56A2,t,2,0,2,0,2.30
1,768274,https://www.airbnb.com/rooms/768274,20230903194145,2023-09-04,city scrape,Rental unit in Amsterdam · ★4.83 · 1 bedroom ·...,Our cool and spacious loft is perfect for a st...,Our neighbourhood is ons of the most beautiful...,https://a0.muscache.com/pictures/27206847/31f5...,3678216,...,4.94,4.86,4.77,0363 7A50 18E7 51D1 B7F9,t,1,1,0,0,0.64
2,768737,https://www.airbnb.com/rooms/768737,20230903194145,2023-09-03,city scrape,Boat in Amsterdam · ★4.82 · 1 bedroom · 1 bed ...,Room to rent in my houseboat. The room has a p...,It is just outside the Jordan in between the c...,https://a0.muscache.com/pictures/1df40445-354f...,3877342,...,4.87,4.72,4.68,036396BE30827DDB9575,t,3,1,2,0,2.73
3,771217,https://www.airbnb.com/rooms/771217,20230903194145,2023-09-04,previous scrape,Houseboat in Amsterdam · ★5.0 · 3 bedrooms · 3...,"Spacious houseboat in Amsterdam, suitable for ...",The houseboat lies in an area with ± 200 house...,https://a0.muscache.com/pictures/57715927/0808...,4068486,...,5.00,4.67,4.56,0363 D807 AD6C 499A F871,f,1,1,0,0,0.11
4,771343,https://www.airbnb.com/rooms/771343,20230903194145,2023-09-03,city scrape,Rental unit in Amsterdam · ★4.89 · 1 bedroom ·...,Royal Bed & Coffee Room with a very comfortabl...,The building is located in Amsterdam centre in...,https://a0.muscache.com/pictures/ea22d262-7456...,2313061,...,4.91,4.96,4.79,0363 8C61 E9B9 5582 913E,f,2,0,2,0,6.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8381,971403658453358540,https://www.airbnb.com/rooms/971403658453358540,20230903194145,2023-09-03,city scrape,Rental unit in Amsterdam · ★New · 1 bedroom · ...,Modern Loft in Vibrant Amsterdam-North<br />Fl...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,6879236,...,NaN,NaN,NaN,0363 9080 FE38 A7CE E7B7,f,1,1,0,0,NaN
8382,971600466535392582,https://www.airbnb.com/rooms/971600466535392582,20230903194145,2023-09-03,city scrape,Home in Amsterdam · ★New · 3 bedrooms · 3 beds...,Plezier met het hele gezin in deze stijlvolle ...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,307559908,...,NaN,NaN,NaN,0363 5639 0AD2 7A88 3FED,f,1,1,0,0,NaN
8383,971686543447319533,https://www.airbnb.com/rooms/971686543447319533,20230903194145,2023-09-03,city scrape,Rental unit in Amsterdam · ★New · 1 bedroom · ...,"Tijdens onze reizen, verhuren we ons gezellige...",Je hebt het gezellige Westerpark als achtertui...,https://a0.muscache.com/pictures/3b180c6c-0c4c...,170194324,...,NaN,NaN,NaN,0363 C287 34D9 EA25 9428,t,1,1,0,0,NaN
8384,971758168481363169,https://www.airbnb.com/rooms/971758168481363169,20230903194145,2023-09-04,city scrape,Hotel in Amsterdam · ★New · 1 bedroom · 1 bed ...,"While we may not be the fanciest hotel, our pr...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,55794534,...,NaN,NaN,NaN,Exempt,f,1,0,1,0,NaN
8385,972218247170836285,https://www.airbnb.com/rooms/972218247170836285,20230903194145,2023-09-03,city scrape,Condo in Amsterdam · ★New · 2 bedrooms · 1 bed...,"Spacious, bright and luxurious apartment with ...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,2876582,...,NaN,NaN,NaN,0363 2F20 4F53 FB57 2D7F,f,1,1,0,0,NaN

In [5]:
df['neighbourhood'].unique()

array(['Amsterdam, North Holland, Netherlands',
       'Amsterdam, Noord-Holland, Netherlands', nan,
       'Amsterdam, NH, Netherlands',
       'De Pijp, North Holland, Netherlands',
       'Watergraafsmeer, North Holland, Netherlands',
       'Zeeburg, North Holland, Netherlands',
       'Amsterdam, Haarlemmerbuurt, Netherlands',
       'Amsterdam, Netherlands',
       'Amsterdam-Zuidoost, North Holland, Netherlands',
       'Amsterdam, Noord Holland, Netherlands',
       'Amsterdam, SN, Netherlands', 'Amsterdam, Holland, Netherlands',
       'Amsterdam Zuidoost, North Holland, Netherlands',
       'Amsterdam Zuid-Oost, Noord-Holland, Netherlands',
       'Amsterdam, Emmy andriessestraat, Netherlands',
       'Amsterdam, AH, Netherlands', 'Amsterdam, GA, Netherlands',
       'Amsterdam, GD, Netherlands', 'Amsterdam, Amstel, Netherlands',
       'Amsterdam-Zuidoost, Noord-Holland, Netherlands',
       'Amsterdam , 2 de Egelantiersdwarsstraat 13 III, Netherlands',
       'Amsterdam, VX, Netherlands', 'Amsterdam, DP, Netherlands',
       'Amsterdam , Noord-Holland, Netherlands',
       'Amsterdam, Frederiksstraat, Netherlands',
       'Amsterdam , North Holland, Netherlands',
       'Duivendrecht, Noord-Holland, Netherlands',
       'Diemen, Noord-Holland, Netherlands', 'Amsterdam, NM, Netherlands',
       'Netherlands', 'Landsmeer, Noord-Holland, Netherlands',
       'Amsterdam, BH, Netherlands', 'Amsterdam, LC, Netherlands',
       'Amsterdam, AA, Netherlands', 'TC Amsterdam, Netherlands',
       'Badhoevedorp, Noord-Holland, Netherlands',
       'LL Amsterdam, Netherlands', 'Amsterdam, LL, Netherlands',
       'Amsterdam-Centrum, Noord-Holland, Netherlands',
       'Amsterdam, Nord Holland, Netherlands',
       'Central Amsterdam, Amsterdam, Netherlands',
       'Amsterdam, North-Holland, Netherlands',
       'Oostzaan, Noord-Holland, Netherlands',
       '1054 ZV, Noord-Holland, Netherlands',
       'Amsterdam, NORTH HOLLAND, Netherlands',
       'Ouder-Amstel, Noord-Holland, Netherlands',
       'Amsterdam , Netherlands', 'Lijnden, Noord-Holland, Netherlands',
       'Amstelveen, Noord-Holland, Netherlands'], dtype=object)

In [6]:
df['neighbourhood_cleansed'].unique()

array(['Noord-Oost', 'Westerpark', 'Zuid', 'Centrum-West', 'Slotervaart',
       'Centrum-Oost', 'Oostelijk Havengebied - Indische Buurt',
       'Buitenveldert - Zuidas', 'IJburg - Zeeburgereiland', 'Oud-Oost',
       'De Pijp - Rivierenbuurt', 'De Baarsjes - Oud-West',
       'Bos en Lommer', 'Watergraafsmeer', 'Oud-Noord', 'Noord-West',
       'Geuzenveld - Slotermeer', 'De Aker - Nieuw Sloten', 'Osdorp',
       'Bijlmer-Centrum', 'Gaasperdam - Driemond', 'Bijlmer-Oost'],
      dtype=object)

In [8]:
df['neighborhood_overview'].unique()

array(["The neighborhood is very green, quiet, safe and specious. You will see the wild rabbits running around, while just about 20 minutes to the absolute centre (central station) by metro/bus. <br /><br />Two shopping centers with supermarkets, bars, restaurants etc. are nearby.<br /><br />It's just a few minutes walk to the Dutch countryside, where you have a great view of the golf field, cows and villages... To reach the huge lake, where connected to the very famous island Marken and fish town Volendam you need 15 minutes by bike to reach.",
       "Our neighbourhood is ons of the most beautiful parts of Amsterdam, you walk around in a 17th century painting. The 'hood' is next to the Jordaan with lots of (coffee) bars, restaurants, authentic shops, boutiques and culture.",
       'It is just outside the Jordan in between the canals and the Westerpark.',
       ...,
       'De pijp is de “place to be”. Hotspot met alle boutiques, winkels, restaurants en nachtleven',
       'In de .buurt zijn veel restaurants, bars en koffietentjes. Op loopafstand van het Oosterpark en dicht bij het centrum',
       'Je hebt het gezellige Westerpark als achtertuin, station Sloterdijk is op loopafstand en met 10 minuten fietsen ben je midden in de Jordaan. Een perfecte plek, gezellig ingericht en prachtig uitzicht over de stad.'],
      dtype=object)

In [4]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [26]:
df = pd.read_csv("data/inside/calendar.csv")
df

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,2818,2023-09-04,f,$69.00,$69.00,3,1125
1,2818,2023-09-05,t,$69.00,$69.00,3,1125
2,2818,2023-09-06,f,$69.00,$69.00,3,1125
3,2818,2023-09-07,f,$69.00,$69.00,3,1125
4,2818,2023-09-08,f,$69.00,$69.00,3,1125
...,...,...,...,...,...,...,...
3060886,972218247170836285,2024-08-28,f,$211.00,$211.00,7,53
3060887,972218247170836285,2024-08-29,f,$211.00,$211.00,7,53
3060888,972218247170836285,2024-08-30,f,$211.00,$211.00,7,53
3060889,972218247170836285,2024-08-31,f,$211.00,$211.00,7,53
3060890,972218247170836285,2024-09-01,f,$211.00,$211.00,7,53

In [27]:
df.columns

Index(['listing_id', 'date', 'available', 'price', 'adjusted_price',
       'minimum_nights', 'maximum_nights'],
      dtype='object')

In [28]:
df = pd.read_csv("data/inside/reviews.csv")
df

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,2818,1191,2009-03-30,10952,Lam,Daniel is really cool. The place was nice and ...
1,2818,1771,2009-04-24,12798,Alice,Daniel is the most amazing host! His place is ...
2,2818,1989,2009-05-03,11869,Natalja,We had such a great time in Amsterdam. Daniel ...
3,2818,2797,2009-05-18,14064,Enrique,Very professional operation. Room is very clea...
4,2818,3151,2009-05-25,17977,Sherwin,Daniel is highly recommended. He provided all...
...,...,...,...,...,...,...
381036,960741424535163805,972330660472096320,2023-09-03,393668288,Daniel,"Una zona ideal, estuvimos muy agusto, el piso ..."
381037,960767462841067104,967997327787863553,2023-08-28,18895543,Steven,I really enjoyed the location of the private r...
381038,960773375593594967,967927701264018749,2023-08-28,235604573,Mukul,"Robert is a great host, he was present in pers..."
381039,960839346651335772,967269084821281975,2023-08-27,201267725,Silvia,"L'appartamento di Ilona è molto carino, nella ..."
381040,961403313350320957,964371267405973311,2023-08-23,303629554,Amélie,Super sejour!!! Je recommande

In [29]:
df.columns

Index(['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'comments'], dtype='object')